#include <iostream>
#include <memory>
#include <string>
#include <cstdlib>

// gRPC Headers
#include <grpcpp/grpcpp.h>
#include "social_network.grpc.pb.h" // Auto-generated by CMake!

// Our Internal Logic
#include "services/FeedService.h"
#include "services/GraphService.h"
#include "include/ThreadPool.h"
#include <sw/redis++/redis++.h>

using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using grpc::Status;

// Namespaces from our .proto file
using social::FeedApi;
using social::CreatePostRequest;
using social::CreatePostResponse;
using social::GetFeedRequest;
using social::GetFeedResponse;

// --- THE BRIDGE ---
// This class connects the gRPC Network requests to our C++ FeedService
class FeedServiceImpl final : public FeedApi::Service {
private:
    std::shared_ptr<services::FeedService> feedService_;

public:
    explicit FeedServiceImpl(std::shared_ptr<services::FeedService> fs) : feedService_(fs) {}

    // 1. API Endpoint: Create a Post
    Status CreatePost(ServerContext* context, const CreatePostRequest* request, CreatePostResponse* reply) override {
        std::cout << "[API] Received CreatePost request from User " << request->user_id() << std::endl;
        
        try {
            // Call our actual C++ logic!
            feedService_->postContent(request->user_id(), request->content());
            
            reply->set_success(true);
            reply->set_message("Post created and fanout triggered successfully!");
            return Status::OK;
        } catch (const std::exception& e) {
            reply->set_success(false);
            reply->set_message(e.what());
            return Status::CANCELLED;
        }
    }

    // 2. API Endpoint: Get the Feed
    Status GetFeed(ServerContext* context, const GetFeedRequest* request, GetFeedResponse* reply) override {
        std::cout << "[API] Received GetFeed request for User " << request->user_id() << std::endl;
        
        int offset = request->offset() > 0 ? request->offset() : 0;
        int limit = request->limit() > 0 ? request->limit() : 20;

        // Fetch from our C++ logic (which fetches from Redis)
        auto posts = feedService_->getFeedForUser(request->user_id(), offset, limit);

        // Convert our C++ Post objects into gRPC Post objects
        for (const auto& p : posts) {
            social::Post* grpcPost = reply->add_posts(); // Adds a new post to the array
            grpcPost->set_id(p->getId());
            grpcPost->set_author_id(p->getUserId());
            grpcPost->set_content(p->getContent());
        }

        return Status::OK;
    }
};

// --- START THE SERVER ---
void RunServer() {
    std::string server_address("0.0.0.0:50051");

    // 1. Initialize Redis & Services
    // Read Redis host from environment variable, default to localhost
    const char* redisHostEnv = std::getenv("REDIS_HOST");
    std::string redisHost = redisHostEnv ? redisHostEnv : "127.0.0.1";
    std::string redisUrl = "tcp://" + redisHost + ":6379";
    auto redis = std::make_shared<sw::redis::Redis>(redisUrl);
    auto threadPool = std::make_shared<ThreadPool>(4);
    auto graphService = std::make_shared<services::GraphService>(redis);
    auto feedService = std::make_shared<services::FeedService>(graphService, threadPool, redis);

    // Provide some dummy data to test with
    feedService->addUser(1, "Mohith");
    feedService->addUser(2, "Maanas");
    graphService->follow(2, 1); // Jeff follows Elon

    // 2. Start gRPC Server
    FeedServiceImpl service(feedService);
    ServerBuilder builder;
    builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
    builder.RegisterService(&service);
    
    std::unique_ptr<Server> server(builder.BuildAndStart());
    std::cout << "Hurray! gRPC Server listening on " << server_address << std::endl;

    server->Wait(); // Block the main thread, keep listening forever
}

int main(int argc, char** argv) {
    try {
        RunServer();
    } catch (const std::exception& e) {
        std::cerr << "Server Crashed: " << e.what() << std::endl;
    }
    return 0;
}