name: C++ Microservice CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# We must grant the pipeline permission to upload packages
permissions:
  contents: read
  packages: write

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # --- CI: Build & Test  ---
    - name: Build and Test Locally
      run: |
        docker compose up -d --build
        sleep 5
        if [ -z "$(docker ps -q -f name=social-api)" ]; then
          echo " API Server container crashed!"
          docker compose logs api-server
          exit 1
        fi
        echo "Server is stable."
        docker compose down

    # --- CD: Publish to Registry  ---
    
    # 1. Log in to GitHub's Docker Registry using an automatic token
    - name: Log in to GitHub Container Registry
      if: github.event_name != 'pull_request' # Only publish when merging to main
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 2. Build the image and push it to the cloud
    - name: Build and Push Docker Image
      if: github.event_name != 'pull_request'
      run: |
        # Docker requires repo names to be 100% lowercase. 
        # This bash command safely converts your GitHub username to lowercase.
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        IMAGE_NAME="ghcr.io/$REPO_OWNER/social-network-api"
        
        echo "Building image: $IMAGE_NAME:v3.0"
        
        # Build the C++ Server image from our Dockerfile
        docker build -t $IMAGE_NAME:v3.0 .
        
        # Tag it as the 'latest' version as well
        docker tag $IMAGE_NAME:v3.0 $IMAGE_NAME:latest
        
        # Push both tags to GitHub!
        docker push $IMAGE_NAME:v3.0
        docker push $IMAGE_NAME:latest